spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/topicify_dev
      auto-index-creation: true
  redis:
    host: localhost
    port: 6379
    database: topicify_dev

springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    enabled: true
    path: /docs/swagger